### ISSUE TITLE
Problem installing RFXCOM node 

### ISSUE THREAD

**Issue by vlak6613** [maxwellhadley/node-red-contrib-rfxcom#105]
Dear Maxwell, I am trying to install rfxcom's nodes, node-red-contrib-rfxcom. But get the same notifications every time.

Do you  have an idea what this could be
Greatings Rémi

2020-08-24T13:39:14.972Z Install : node-red-contrib-rfxcom 2.11.2

2020-08-24T13:39:15.065Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-rfxcom@2.11.2
2020-08-24T13:39:37.721Z [out]
2020-08-24T13:39:37.721Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-08-24T13:39:37.721Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-08-24T13:39:37.721Z [out]
2020-08-24T13:39:38.818Z [err] prebuild-install
2020-08-24T13:39:38.819Z [err]
2020-08-24T13:39:38.819Z [err] WARN
2020-08-24T13:39:38.819Z [err]
2020-08-24T13:39:38.820Z [err] install
2020-08-24T13:39:38.820Z [err] No prebuilt binaries found (target=12.17.0 runtime=node arch=arm64 libc=musl platform=linux)
2020-08-24T13:39:41.554Z [err] gyp
2020-08-24T13:39:41.555Z [err]
2020-08-24T13:39:41.555Z [err] ERR! build error
2020-08-24T13:39:41.556Z [err] gyp
2020-08-24T13:39:41.557Z [err] ERR!
2020-08-24T13:39:41.557Z [err] stack
2020-08-24T13:39:41.557Z [err] Error: not found: make
2020-08-24T13:39:41.557Z [err] gyp ERR!
2020-08-24T13:39:41.557Z [err] stack at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-08-24T13:39:41.557Z [err] gyp ERR!
2020-08-24T13:39:41.557Z [err] stack at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-08-24T13:39:41.557Z [err] gyp ERR!
2020-08-24T13:39:41.558Z [err] stack
2020-08-24T13:39:41.558Z [err] at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-08-24T13:39:41.558Z [err] gyp
2020-08-24T13:39:41.558Z [err] ERR! stack
2020-08-24T13:39:41.558Z [err] at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-08-24T13:39:41.558Z [err] gyp
2020-08-24T13:39:41.558Z [err] ERR!
2020-08-24T13:39:41.558Z [err] stack at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-08-24T13:39:41.558Z [err] gyp
2020-08-24T13:39:41.558Z [err] ERR! stack
2020-08-24T13:39:41.558Z [err] at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-08-24T13:39:41.558Z [err] gyp
2020-08-24T13:39:41.558Z [err] ERR! stack
2020-08-24T13:39:41.558Z [err] at FSReqCallback.oncomplete (fs.js:167:21)
2020-08-24T13:39:41.559Z [err] gyp
2020-08-24T13:39:41.559Z [err] ERR! System Linux 4.19.127-v8
2020-08-24T13:39:41.559Z [err] gyp
2020-08-24T13:39:41.559Z [err] ERR! command
2020-08-24T13:39:41.560Z [err] "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-08-24T13:39:41.560Z [err] gyp ERR!
2020-08-24T13:39:41.560Z [err] cwd /config/node-red/node_modules/@serialport/bindings
2020-08-24T13:39:41.560Z [err] gyp
2020-08-24T13:39:41.560Z [err] ERR! node -v
2020-08-24T13:39:41.560Z [err] v12.17.0
2020-08-24T13:39:41.560Z [err] gyp
2020-08-24T13:39:41.560Z [err] ERR! node-gyp -v v5.1.0
2020-08-24T13:39:41.560Z [err] gyp ERR!
2020-08-24T13:39:41.560Z [err] not ok
2020-08-24T13:39:42.533Z [err] npm
2020-08-24T13:39:42.533Z [err] ERR! code ELIFECYCLE
2020-08-24T13:39:42.533Z [err] npm ERR!
2020-08-24T13:39:42.534Z [err] errno 1
2020-08-24T13:39:42.538Z [err] npm
2020-08-24T13:39:42.538Z [err] ERR! @serialport/bindings@8.0.8 install: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-08-24T13:39:42.538Z [err] npm ERR! Exit status 1
2020-08-24T13:39:42.538Z [err] npm
2020-08-24T13:39:42.538Z [err] ERR!
2020-08-24T13:39:42.538Z [err]
2020-08-24T13:39:42.538Z [err] npm
2020-08-24T13:39:42.539Z [err] ERR! Failed at the @serialport/bindings@8.0.8 install script.
2020-08-24T13:39:42.539Z [err] npm ERR!
2020-08-24T13:39:42.539Z [err] This is probably not a problem with npm. There is likely additional logging output above.
2020-08-24T13:39:42.588Z [err]
2020-08-24T13:39:42.589Z [err] npm ERR! A complete log of this run can be found in:
2020-08-24T13:39:42.589Z [err] npm
2020-08-24T13:39:42.589Z [err] ERR!
2020-08-24T13:39:42.589Z [err] /root/.npm/_logs/2020-08-24T13_39_42_557Z-debug.log
2020-08-24T13:39:42.622Z rc=1

2020-08-24T13:40:28.532Z Install : node-red-contrib-rfxcom 2.11.2

2020-08-24T13:40:28.836Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-rfxcom@2.11.2
2020-08-24T13:40:44.342Z [out]
2020-08-24T13:40:44.342Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-08-24T13:40:44.342Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-08-24T13:40:44.342Z [out]
2020-08-24T13:40:45.403Z [err] prebuild-install
2020-08-24T13:40:45.403Z [err] WARN
2020-08-24T13:40:45.404Z [err] install No prebuilt binaries found (target=12.17.0 runtime=node arch=arm64 libc=musl platform=linux)
2020-08-24T13:40:47.462Z [err] gyp
2020-08-24T13:40:47.463Z [err]
2020-08-24T13:40:47.463Z [err] ERR! build error
2020-08-24T13:40:47.465Z [err] gyp
2020-08-24T13:40:47.465Z [err]
2020-08-24T13:40:47.465Z [err] ERR!
2020-08-24T13:40:47.465Z [err] stack
2020-08-24T13:40:47.465Z [err] Error: not found: make
2020-08-24T13:40:47.465Z [err] gyp
2020-08-24T13:40:47.465Z [err] ERR!
2020-08-24T13:40:47.465Z [err] stack
2020-08-24T13:40:47.465Z [err] at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-08-24T13:40:47.465Z [err] gyp
2020-08-24T13:40:47.465Z [err] ERR!
2020-08-24T13:40:47.465Z [err] stack
2020-08-24T13:40:47.466Z [err] at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-08-24T13:40:47.466Z [err] gyp
2020-08-24T13:40:47.466Z [err] ERR! stack at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-08-24T13:40:47.466Z [err] gyp ERR!
2020-08-24T13:40:47.466Z [err] stack at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-08-24T13:40:47.466Z [err] gyp
2020-08-24T13:40:47.466Z [err] ERR!
2020-08-24T13:40:47.466Z [err] stack at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-08-24T13:40:47.466Z [err] gyp
2020-08-24T13:40:47.466Z [err] ERR!
2020-08-24T13:40:47.466Z [err] stack at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-08-24T13:40:47.467Z [err] gyp ERR!
2020-08-24T13:40:47.467Z [err] stack at FSReqCallback.oncomplete (fs.js:167:21)
2020-08-24T13:40:47.467Z [err] gyp
2020-08-24T13:40:47.467Z [err] ERR! System Linux 4.19.127-v8
2020-08-24T13:40:47.468Z [err] gyp
2020-08-24T13:40:47.468Z [err] ERR! command
2020-08-24T13:40:47.468Z [err] "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-08-24T13:40:47.468Z [err] gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2020-08-24T13:40:47.468Z [err] gyp ERR!
2020-08-24T13:40:47.468Z [err] node -v
2020-08-24T13:40:47.468Z [err] v12.17.0
2020-08-24T13:40:47.468Z [err] gyp
2020-08-24T13:40:47.468Z [err] ERR! node-gyp -v
2020-08-24T13:40:47.468Z [err] v5.1.0
2020-08-24T13:40:47.468Z [err] gyp
2020-08-24T13:40:47.469Z [err] ERR! not ok
2020-08-24T13:40:47.469Z [err]
2020-08-24T13:40:48.517Z [err] npm
2020-08-24T13:40:48.517Z [err] ERR! code ELIFECYCLE
2020-08-24T13:40:48.517Z [err] npm ERR!
2020-08-24T13:40:48.518Z [err] errno 1
2020-08-24T13:40:48.523Z [err] npm
2020-08-24T13:40:48.523Z [err] ERR! @serialport/bindings@8.0.8 install: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-08-24T13:40:48.523Z [err] npm
2020-08-24T13:40:48.524Z [err] ERR! Exit status 1
2020-08-24T13:40:48.524Z [err] npm
2020-08-24T13:40:48.524Z [err] ERR!
2020-08-24T13:40:48.524Z [err] npm ERR!
2020-08-24T13:40:48.524Z [err] Failed at the @serialport/bindings@8.0.8 install script.
2020-08-24T13:40:48.524Z [err] npm
2020-08-24T13:40:48.524Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-08-24T13:40:48.564Z [err]
2020-08-24T13:40:48.565Z [err] npm
2020-08-24T13:40:48.566Z [err]
2020-08-24T13:40:48.566Z [err] ERR!
2020-08-24T13:40:48.568Z [err] A complete log of this run can be found in:
2020-08-24T13:40:48.570Z [err] npm ERR! /root/.npm/_logs/2020-08-24T13_40_48_540Z-debug.log
2020-08-24T13:40:48.603Z rc=1

**Comment by maxwellhadley** [comment]
The installer is trying to compile the C++ source files for `serialport` and can't find the `make` command. You need to install the build tools using your Linux distribution's package manger.

**Comment by vlak6613** [comment]
hi Maxwell, i am not very proficient with linux. But I have running hassio on an rpi and installed the addon from node red. Do you happen to have an example of how to do this in my situation?

**Comment by maxwellhadley** [comment]
Check [here](https://github.com/maxwellhadley/node-red-contrib-rfxcom/issues/90#issuecomment-590103316)

**Comment by sabamimi** [comment]
Yes, I had the same issue.
If you add:

 system_packages:
  - make
  - python3
  - g++
  - gcc
  - linux-headers
npm_packages:
  - nan - serialport - node-red-contrib-rfxcom_

in the node red config parameters
(Supervisor -> Node-RED -> Configuration)

.....the problem is solved.

**Comment by maxwellhadley** [comment]
Since I haven't heard from @vlak6613 in a while, I am closing the issue
