### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by onokje** [maxwellhadley/node-red-contrib-rfxcom#119]
Hi, I tried to install this node (using the palette manager in node-red) but the installation failed. Logs:

```
-----------------------------------------------------------
2021-11-19T14:13:38.722Z Install : node-red-contrib-rfxcom 2.11.3

2021-11-19T14:13:38.749Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-rfxcom@2.11.3
2021-11-19T14:13:47.323Z [err] npm ERR! code 1
2021-11-19T14:13:47.323Z [err] npm ERR! path /config/node-red/node_modules/@serialport/bindings
2021-11-19T14:13:47.325Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  command failed
2021-11-19T14:13:47.326Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-11-19T14:13:47.326Z [err] npm ERR! prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=x64 libc=musl platform=linux)
2021-11-19T14:13:47.326Z [err] npm 
2021-11-19T14:13:47.326Z [err] ERR! gyp info it worked if it ends with ok
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info using node-gyp@7.1.2
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info using node@14.18.1 | linux | x64
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn /usr/bin/python3
2021-11-19T14:13:47.326Z [err] npm 
2021-11-19T14:13:47.326Z [err] ERR! gyp info spawn args [
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-f',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   'make',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-19T14:13:47.326Z [err] npm 
2021-11-19T14:13:47.326Z [err] ERR! gyp info spawn args   '/config/node-red/node_modules/@serialport/bindings/build/config.gypi',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-I',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.18.1/include/node/common.gypi',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-11-19T14:13:47.326Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  gyp info spawn args   '-Dvisibility=default',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.18.1',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.18.1/<(target_arch)/node.lib',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/@serialport/bindings',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-11-19T14:13:47.326Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  gyp info spawn args   '--depth=.',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '--generator-output',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   'build',
2021-11-19T14:13:47.326Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2021-11-19T14:13:47.326Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  gyp info spawn args ]
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! build error 
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack Error: not found: make
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-11-19T14:13:47.326Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  gyp ERR! stack     at new Promise (<anonymous>)
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-11-19T14:13:47.326Z [err] npm
2021-11-19T14:13:47.326Z [err]  ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! System Linux 5.10.75
2021-11-19T14:13:47.326Z [err] npm ERR!
2021-11-19T14:13:47.326Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! node -v v14.18.1
2021-11-19T14:13:47.326Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-11-19T14:13:47.326Z [err] npm 
2021-11-19T14:13:47.326Z [err] ERR! gyp ERR! not ok
2021-11-19T14:13:47.337Z [err] 
2021-11-19T14:13:47.337Z [err] npm ERR! A complete log of this run can be found in:
2021-11-19T14:13:47.337Z [err] npm ERR!     /root/.npm/_logs/2021-11-19T14_13_47_328Z-debug.log
2021-11-19T14:13:47.343Z rc=1
```

I am using the latest version of Home assistant OS. Node red version: 2.1.3
Any ideas?

**Comment by maxwellhadley** [comment]
I think this is the same problem as #105 - missing build tools, see the comments for how to fix it
