### ISSUE TITLE
Error: Method Not Allowed during npm install

### ISSUE THREAD

**Issue by davidbouche** [maxwellhadley/node-red-contrib-rfxcom#61]
Hello,

Here's the command I launched and the error I've encountred : 

```
pi@raspberrypi:~ $ sudo npm install -g node-red-contrib-rfxcom
(node:8993) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.71-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-red-contrib-rfxcom"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

If you need more informations to help me to install this extensions, I will answer.

Thanks for your support,
David.

**Comment by davidbouche** [comment]
It seems that it comme from a too old version of npm. Have to install it manually.

**Comment by maxwellhadley** [comment]
Sorry, I only just saw this. That is a *very* old version of npm!
